<?php $_sample = $this->getCollection(); ?>
<?php if ($_sample->getSize()): ?>
<div class="sample_list_view">
    <?php foreach ($_sample as $sampleItem): ?>
        <div id="item_<?php echo $sampleItem->getId() ?>" class="sample_list_item">
            <h2>
                <a href="<?php echo $this->getItemUrl($sampleItem) ?>">
                    <?php echo $this->escapeHtml($sampleItem->getTitle()) ?>
                </a>
            </h2>

            <div class="sample_item_subtitle">
                <?php echo $this->formatDate($sampleItem->getPublishedAt()) ?> |
                <?php echo $this->escapeHtml($sampleItem->getAuthor()) ?>
            </div>

            <?php if ($imageUrl = $this->getImageUrl($sampleItem, 100)): ?>
               <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($sampleItem->getTitle()); ?>" /></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->getPager() ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no Sample.'); ?></span></div>
<?php endif ?>
