<?php
/**
 * Sample template for separate item
 *
 */

/**
 * @var $this Tutorial\Sample\Block\View
 * @see Tutorial\Sample\Block\View
 */
?>
<?php $_sampleItem = $this->getSample(); ?>
    <div class="sample_item_subtitle">
        <?php echo $this->formatDate($_sampleItem->getPublishedAt()) ?> |
        <?php echo $this->escapeHtml($_sampleItem->getAuthor()) ?>
    </div>

<div class="sample_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_sampleItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_sampleItem->getTitle()) ?>" /></p>
    <?php endif; ?>

    <div class="sample_item_content"><?php echo $_sampleItem->getContent() ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo __('Return to list') ?>
        </a>
    </div>
</div>